## Basic set

In [1]:
import os, sys, random, struct, argparse
import numpy as np
np.set_printoptions(precision=16)

In [2]:
sys.path.remove('/home/jungeun/.local/lib/python3.6/site-packages')

In [3]:
import torch
sys.path.append('/home/jungeun/.local/lib/python3.6/site-packages')

In [4]:
parser = argparse.ArgumentParser(description='fixed_mac')
parser.add_argument('--full_bits', type=int, default=16, help='Number of Quantization Bits')
parser.add_argument('--frac_bits', type=int, default=7, help='Number of Quantization Bits')
parser.add_argument('--bBW', type=int, default=7, help='Number of bit width')
args = parser.parse_args(args=[])

## Integer -> Two's Complemenet Binary

In [5]:
def int2bin(iIn,iBW):
    iBW = iBW + 1
    if iIn >= 0:
        bOut = bin(iIn).replace('0b','').rjust(iBW,'0')
    else :
        bOut = bin(iIn & (pow(2,iBW)-1)).replace('0b','').rjust(iBW,'1')
    return bOut[1:]

## XOR gate

In [6]:
def XOR(iA,iB):
    if iA != iB :
        iOut = 1
    else :
        iOut = 0
    return iOut

In [7]:
2**-1

0.5

In [8]:
def FindFraction(bIn):
    s = 0
    for i in range(len(bIn)):
        if bIn[i] == '1' :
            s = s + 2**(-(i+1))
    return s

In [9]:
def binInv(bIn):
    bOut = bin(int(bIn,2)^(pow(2,len(bIn))-1)).replace('0b','').rjust(len(bIn),'0')
    return bOut

In [10]:
10111010
FindFraction('10111010')

0.7265625

## Fixed

In [11]:
class fxp:
    def __init__(self, bIn, iBWF):
        self.iFullBW = len(bIn)
        self.iIntgBW = self.iFullBW - iBWF
        self.bSign = bIn[0]
        self.bIntg = bIn[:self.iIntgBW]
        self.bFrac = bIn[self.iIntgBW:]
        self.fFull = 0
        try:
            for idx, bit in enumerate(bIn):
                if idx == 0:
                    self.fFull = self.fFull + int(bit,2) * -pow(2, self.iIntgBW - 1)
                else:
                    self.fFull = self.fFull + int(bit,2) * pow(2, self.iIntgBW - 1 - idx)
        except:
            print(bIn)
        self.dispFull = self.bIntg +"."+ self.bFrac 
        return

In [12]:
class flp2fix:
    def __init__(self, fIn, iBW, iBWF):
        self.fMin = - 2 ** (iBW - iBWF - 1)
        self.fMax = (2 ** (iBW-1) - 1) * (2 ** -iBWF)
        self.fResol		= 2 ** -iBWF
        if fIn < self.fMin or fIn > self.fMax:
            print(f'({fIn}): Out of input range ({self.fMax}/{self.fMin}) during flp -> fix converting ')
        self.iBW = iBW
        self.iBWI = iBW - iBWF
        self.iBWF = iBWF

        self.iFLP2INT = abs(int(fIn * 2 ** iBWF))
        if fIn < 0:
            self.iFLP2INT = 2 ** (iBW-1) - self.iFLP2INT

        if fIn >= 0:
            self.bFull = bin(self.iFLP2INT)[2:].rjust(iBW, '0')
        else:
            self.bFull = '1'+bin(self.iFLP2INT)[2:].rjust(iBW-1, '0')
            if len(self.bFull) > iBW:
                self.bFull = '0' * iBW

        self.cssFxp = fxp(self.bFull, self.iBWF)
        self.bSign = self.cssFxp.bSign
        self.bIntg = self.cssFxp.bIntg
        self.bFrac = self.cssFxp.bFrac
        self.fFull = self.cssFxp.fFull
        return

In [13]:
def flp2fixTensor(fIn, iBW, iBWF):
    fMin = - 2 ** (iBW - iBWF - 1)
    fMax = (2 ** (iBW-1) - 1) * (2 ** -iBWF)
    fList = []
    for aTensor in fIn.view(-1):
        fList.append(flp2fix(aTensor, iBW, iBWF).fFull)
    return torch.tensor(fList).view(fIn.size())

In [14]:
class LFSR7:
    def Random(self):
        self.b0 = eval(f'str(random.randint(0,1))')
        self.b1 = eval(f'str(random.randint(0,1))')
        self.b2 = eval(f'str(random.randint(0,1))')
        self.b3 = eval(f'str(random.randint(0,1))')
        self.b4 = eval(f'str(random.randint(0,1))')
        self.b5 = eval(f'str(random.randint(0,1))')
        self.b6 = eval(f'str(random.randint(0,1))')
        if int(self.b0) + int(self.b1) + int(self.b2) + int(self.b3) + int(self.b4) + int(self.b5) + int(self.b6) == 0 :
            self.b0 = eval(f'str(random.randint(0,1))')
            self.b1 = eval(f'str(random.randint(0,1))')
            self.b2 = eval(f'str(random.randint(0,1))')
            self.b3 = eval(f'str(random.randint(0,1))')
            self.b4 = eval(f'str(random.randint(0,1))')
            self.b5 = eval(f'str(random.randint(0,1))')
            self.b6 = eval(f'str(random.randint(0,1))')
        return self.b0 + self.b1 + self.b2 + self.b3 + self.b4 + self.b5 + self.b6
    
    def Normal(self,stream):
        self.b0 = str(XOR(int(stream[5]),int(stream[6])))
        self.b1 = str(stream[0])
        self.b2 = str(stream[1])
        self.b3 = str(stream[2])
        self.b4 = str(stream[3])
        self.b5 = str(stream[4])
        self.b6 = str(stream[5])
        
        return self.b0 + self.b1 + self.b2 + self.b3 + self.b4 + self.b5 + self.b6
    
    def Allzero(self):
        self.b0 = '0'
        self.b1 = '0'
        self.b2 = '0'
        self.b3 = '0'
        self.b4 = '0'
        self.b5 = '0'
        self.b6 = '0'
        
        return self.b0 + self.b1 + self.b2 + self.b3 + self.b4 + self.b5 + self.b6

In [15]:
def LFSRlist7():
    lfsr = LFSR7()
    lfsrlist = []
    for k in range(2**(args.bBW)-1): #lfsr number generating
        if k == 0:
            lfsrlist.append(lfsr.Random())
        else :
            lfsrlist.append(lfsr.Normal(lfsrlist[k-1]))
        if (k == 2**(args.bBW)-2):
            lfsrlist.append(lfsr.Allzero())
    
    if (args.bBW) != args.frac_bits :
        if args.bBW < args.frac_bits :
            for i in range(len(lfsrlist)):
                lfsrlist[i] = lfsrlist[i] + (args.frac_bits-args.bBW)*'0'
        else :
            print("it can't work")
            return 0
    
    return lfsrlist

## Comparator

In [16]:
def Comp(a,lfsr,snum): #lfsr number < origin number , output = 1
    for com in range(0,len(a)):
        oA = 0
        if a[com]!=lfsr[com]:
            if(int(a[com]) > int(lfsr[com])):
                oA = 1
            else :
                oA = 0
            break
    return XOR(oA,snum)

## SNUM

In [17]:
def snum(a):
    if a >= 0 :
        return 0
    else :
        return 1

## SNG module

In [18]:
def SNG(iIN,lfsr):
    if iIN == 1:
        iIN = 0.9999
    sNUM = snum(iIN)
    
    bIN = flp2fix(iIN,args.full_bits,args.frac_bits).bFull
    bFRAC = bIN[-(args.frac_bits):]
    oAlist = []
    
    for k in range(2**(args.bBW)): #lfsr number generating
        lNUM = lfsr[k]
        a = Comp(bFRAC,lNUM,sNUM)
        oAlist.append(a) #comparator of input a
    
    oAlist.insert(0,sNUM)
    #sA = "".join(oAlist)
    if bIN == args.full_bits*'0' :
        return torch.zeros((2**args.bBW)+1)
    else :
        return torch.tensor(oAlist)

In [19]:
def SNGtensor(fIn,lfsr):
    sList = []
    fsize = list(fIn.size())
    fsize.insert(2,(2**args.bBW)+1)
    for aTensor in fIn.view(-1):
        sList.append(SNG(aTensor,lfsr))
    
    c = torch.stack(sList,0)
    return c.view(fsize)

In [20]:
def CountOne(nIn):
    nlist = []
    for num in nIn.view(-1,nIn.size()[-1]):
        n = 0
        for a in num:
            if a == 1 :
                n += 1
        if num[0] == 1 :
            nlist.append(n-1)
        else :
            nlist.append(n)
    return torch.tensor(nlist).view(nIn.size()[0],nIn.size()[1])

In [21]:
def defSign(nIn):
    nlist = []
    for num in nIn.view(-1,nIn.size()[-1]):
        if num[0] == 1 :
            nlist.append(-1)
        else :
            nlist.append(1)
    return torch.tensor(nlist).view(nIn.size()[0],nIn.size()[1])

In [22]:
def S2None(sIn):
    s = defSign(sIn)
    n = CountOne(sIn)
    o = (n/(2**args.bBW))*s
    return o

In [30]:
a = torch.rand((2,3))-torch.randint(4,(2,3))+torch.randint(4,(2,3))
b = flp2fixTensor(a,args.full_bits,args.frac_bits)
max = torch.max(b)
lfsr = LFSRlist7()
e = SNGtensor(b/max,lfsr)
eb = e.view(e.size()[1],e.size()[0],-1)
f = S2None(e)
fb = S2None(eb)
print(b/max)
print(f)
print(fb)

tensor([[-0.0054,  0.5957,  0.9057],
        [ 1.0000, -0.5094,  0.0135]])
tensor([[ 0.0000,  0.5938,  0.8984],
        [ 0.9922, -0.5078,  0.0078]])
tensor([[ 0.0000,  0.5938],
        [ 0.8984,  0.9922],
        [-0.5078,  0.0078]])


In [32]:
print(e.size())
print(eb.size())

torch.Size([2, 3, 129])
torch.Size([3, 2, 129])


In [25]:
for i in range(100):
    a = random.random()
    b = flp2fix(a,args.full_bits,args.frac_bits).fFull
    c = flp2fix(a,args.full_bits,args.frac_bits).bFull
    d = flp2fix(b,args.full_bits,args.frac_bits).fFull
    lfsr = LFSRlist7()
    
    e = SNG(b,lfsr)
    f = S2None(e)
    print(b)
    print(f)
    k = 0
    if b!=f :
        for n in range(len(e)) :
            print(e[n].item(), end = '')
            if e[n] == 1 :
                k += 1
    print('')
    print(k)
    
    


IndexError: tuple index out of range